apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  labels:
    app: workers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
      - name: workers
        image: ghcr.io/section/workersdemo:0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".1"
            memory: ".1Gi"
          limits:
            cpu: ".1"
            memory: ".1Gi"
        ports:
        - containerPort: 3000
